spring:
  application:
    name: ArgusAPI

  datasource:
    url: jdbc:mysql://localhost:3306/argus_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: db123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: true
api:
  security:
    token:
      secret: "${JWT_SECRET:my-secret-key}"