version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbArgus:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db123
      MYSQL_DATABASE: argus_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbArgus:

