CREATE TABLE IF NOT EXISTS `ocorrencias` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tipo` ENUM('PROBLEMA_DE_INFRAESTRUTURA', 'DESENTENDIMENTO', 'SOLICITACAO_DE_MANUTENCAO', 'ASSEMBLEIA', 'DESVIO_DE_CONDUTA') NOT NULL,
  `status_aprovacao` ENUM('APROVADO', 'REJEITADO', 'AGUARDANDO') DEFAULT 'AGUARDANDO',
  `status_resolucao` ENUM('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA') NOT NULL DEFAULT 'PENDENTE',
  `data_criacao` DATETIME NOT NULL,
  `feedback` TEXT NULL,
  `id_usuario` BIGINT NOT NULL,
  `id_area` BIGINT,
  FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id`),
  FOREIGN KEY (`id_area`) REFERENCES `areas_comuns` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
